\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Statistical Methods for Discrete Response, Time Series, and Panel Data: Live ession 4},
            pdfauthor={Professor Jeffrey Yau},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Statistical Methods for Discrete Response, Time Series, and Panel Data:
Live ession 4}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Professor Jeffrey Yau}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\section{Main Topics Covered in Lecture
4:}\label{main-topics-covered-in-lecture-4}

\begin{itemize}
\tightlist
\item
  Multinomial probability distribution
\item
  \(IJ\) contingency tables and inference using contingency tables
\item
  The notion of independence
\item
  Nominal response models
\item
  Odds ratios in the context of nominal response models
\item
  Ordinal logistical regression model
\item
  Estimation and statistical inference of these models
\end{itemize}

\section{Required Readings:}\label{required-readings}

\textbf{BL2015:} Christopher R. Bilder and Thomas M. Loughin. Analysis
of Categorical Data with R. CRC Press. 2015.

\begin{itemize}
\tightlist
\item
  Ch.3 (Skip Sections 3.4.3, 3.5)
\end{itemize}

\section{Agenda of Week 4 Live
Session}\label{agenda-of-week-4-live-session}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Quiz 3
\item
  An Application of Multinomial Logistic Regressoin: Modeling Voters'
  Party - Evidence from the 2016 American National Election Survey
\end{enumerate}

\newpage

\section{Recap some notations:}\label{recap-some-notations}

\begin{itemize}
\item
  joint probability of the counts \(N_j\)
\item
  relationship among multiple multinomial random variables: \(Y_i\)
\end{itemize}

\$\pi\emph{j = P(Y = j) \text{ where } j = 1,\dots,J \text{ and }
\sum}\{j=1\}\^{}J \pi\_j = 1 \$

Given \(n\) ``\emph{identical}'' trials, \(Y_1, \dots Y_n\)

\(N_j = \sum_{i=1}^n I(Y_i = y)\)

\(\sum_{j=1}^J n_j= 0\)

\textbf{Mulitnomial Probability Distribution:} The pmf for observation a
particular set of counts \(n_1,\dots,n_J\) (from \textbf{one}
multinomial random variable) is \[
P(N_1 = n_1, \dots, N_J = n_J) = \frac{n!}{\prod_{j=1}^J n_j!}\prod_{j=1}^J P(Y=j)^{n_j} = \frac{n!}{\prod_{j=1}^J n_j!}\prod_{j=1}^J \pi_j^{n_j}
\]

\textbf{Two Multinomial Random Variables}

\textbf{\(I \times J\) contingency tables}

Two categorical variables: \(X \text{ and } Y\)

\((X=i,Y=j)\)

\(N_{ij}, i=1,\dots,I, j=1,\dots,J\)

\(n_{+j} = \sum_{i=1}^I n_{ij}\) the total for column \(j\)

\(n_{i+} = \sum_{j=1}^J n_{ij}\) the total for row \(i\)

\(n_{++} = n\)

\[
P(N_{11} = n_{11}, \dots, N_{IJ} = n_{IJ}) =
\frac{n!}{\prod_{i=1}^I \prod_{j=1}^J n_{ij}!} \prod_{i=1}^I \prod_{j=1}^J P(X=i, Y=j)^{n_{ij}}
\]

Marginal distribution for \(X\): \$ \pi\_\{+\} = P(X=i) \text{ for } i =
1,\dots,I\$, which is multinomial with \(n\) trials and probabilities
\(\pi_{1+},\dots\pi_{I+}\) and with marginal counts
\(n_{1+},\dots, n_{I+}\)

The marginal distribution for \(Y\) can be defined in a similar manner.

When \(X\) does not affect the probabilities for the outcome of \(Y\),
we say that \(Y\) is independent of \(X\):
\(\pi_{ij} = \pi_{i+} \pi_{+j}\)

\newpage

\section{Introduction - Multinomial Logistic
Regression}\label{introduction---multinomial-logistic-regression}

Modeling the probabilities of a categorical response variable \(Y\) with
response categories \(j = 1, \dots, J\) using explanatory varibles
\(x_1,\dots,x_p\).

We use odds to compare any pair of response categories:
\(\frac{\pi_j}{\pi_{j'}}\)

Fix one of the categories as the base level, and model \(J-1\)
categories with respect to this level.

Assuming category \(1\) as the base level, the multinomial logistic
regression is expressed as

\[
log \left( \frac{\pi_j}{\pi_1} \right) = \beta_{j0} + \beta_{j1} x_1 + \cdots + \beta_{jp} x_p
\] for \(j = 2, \dots , J\)

\begin{itemize}
\tightlist
\item
  Notice that each response's log-odds relate to the explanatory
  variables in a different way.
\end{itemize}

\[
  \pi_1 = \frac{1}{1 + \sum_{j=2}^J exp(\beta_0 + \beta_{j1}x_1 + \cdots + \beta_{jp}x_p) }
\]

\[
  \pi_j = \frac{exp(\beta_0 + \beta_{j1}x_1 + \cdots + \beta_{jp}x_p)}{1 + \sum_{j=2}^J exp(\beta_0 + \beta_{j1}x_1 + \cdots + \beta_{jp}x_p) }
\] for \(j = 2, \dots , J\)

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

In this exercise, we want to model voters' self identified party
affiliation using their demographic characteristic and a handful of
self-indentifying variables.The data was obtained from the
\textbf{American National Election Survey}, which conducted a survey
several months prior to the \(2016\) American Presidential elections.
\emph{Note that the original survey data uses survey weights, which we
will not use here.}

The dataset ``\emph{w271\_LiveSession04\_data.csv}'' contains a handful
of variables from the survey, and these variables have been cleaned and
modified for this exercise. This dataset contains the following
variables:

\begin{longtable}[]{@{}ll@{}}
\toprule
\begin{minipage}[b]{0.37\columnwidth}\raggedright\strut
\textbf{Variable Name}\strut
\end{minipage} & \begin{minipage}[b]{0.57\columnwidth}\raggedright\strut
\textbf{Explanations}\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
ftwhite, ftblack, ftmuslim\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
Feeling thermometer variables where respondents are asked to rate their
favorability of whites, blacks, and muslims, on a 0 -- 100 scale.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
Presjob\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
A seven point scale indicating respondents' evaluation of President
Obama. 1 = Very strongly approve; 7 = Very strongly disapprove\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
Srv\_spend\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
Seven point scale representing the degree to which respondents believe
that the government should provide or should not provide services: 1 =
Government should provide many fewer services; 7 = Government should
provide many more services.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
crimespend\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
A seven point scale representing degree to which respondents think that
the federal government should or should not increase federal spending on
crime. 1 = Increased a great deal; 7 = Decreased a great deal\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
ideo5\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
A five point scale of respondents' self reported ideology. 1 = Very
liberal; 5 = Very conservative\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
party\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
Categorical variable indicating respondents' party affiliation:
Democrat, Independent, Republican\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
age\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
Respondents' age, as of 2016.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
race\_white\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
Dummy variable taking a value of one if the respondent is white and is
zero otherwise.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
-----------------------------\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
----------------------------------------------\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.37\columnwidth}\raggedright\strut
female\strut
\end{minipage} & \begin{minipage}[t]{0.57\columnwidth}\raggedright\strut
Dummy variable taking a value of one if the respondent is female and is
zero otherwise.\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

The US has two major political parties. The Democratic Party is
considered to be the ideologically libearl party while the Republican
Party is considered to be the ideologically conservative party. A
non-trivial proportion of American voters either identify themselves as
being Independnet or supporting other parties. In this dataset, voters
identify themselves as Democratic, Republican, or Independent.

\section{EDA}\label{eda}

Setup Codes and Load Data

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(}\DataTypeTok{list =} \KeywordTok{ls}\NormalTok{())}

\NormalTok{knitr::opts_chunk$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{tidy.opts=}\KeywordTok{list}\NormalTok{(}\DataTypeTok{width.cutoff=}\DecValTok{60}\NormalTok{),}\DataTypeTok{tidy=}\OtherTok{TRUE}\NormalTok{)}

\CommentTok{# Load Libraries}
\KeywordTok{library}\NormalTok{(car)}
\KeywordTok{library}\NormalTok{(Hmisc)}
\KeywordTok{library}\NormalTok{(skimr)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(stargazer)}
\KeywordTok{library}\NormalTok{(gmodels) }\CommentTok{# For cross tabulation (SAS and SPSS style)}

\KeywordTok{library}\NormalTok{(MASS)}
\KeywordTok{library}\NormalTok{(mcprofile)}
\KeywordTok{library}\NormalTok{(vcd)}
\KeywordTok{library}\NormalTok{(nnet)}

\CommentTok{#path <- "~/Documents/Teach/Cal/w271/course-main-dev/live-session-files/week04"}
\CommentTok{#setwd(path)}

\NormalTok{df <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"w271_LiveSession04_data.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{sep =} \StringTok{","}\NormalTok{)}

\CommentTok{# Make data}
\KeywordTok{library}\NormalTok{(plyr)}
\KeywordTok{str}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1200 obs. of  11 variables:
##  $ ftwhite   : int  100 74 50 64 58 51 70 70 50 90 ...
##  $ ftblack   : int  100 6 50 61 61 50 100 70 50 75 ...
##  $ ftmuslim  : int  20 22 5 61 22 11 100 40 12 72 ...
##  $ presjob   : int  1 3 7 2 7 7 2 7 7 2 ...
##  $ srv_spend : int  7 6 2 6 1 1 7 3 1 6 ...
##  $ crimespend: int  5 2 5 4 4 7 2 4 4 3 ...
##  $ party     : chr  "Democrat" "Independent" "Republican" "Democrat" ...
##  $ ideo5     : int  NA 2 4 2 4 4 1 5 4 2 ...
##  $ age       : int  56 59 53 36 42 58 38 65 43 80 ...
##  $ race_white: int  1 1 1 1 1 1 1 1 1 1 ...
##  $ female    : int  0 1 0 0 0 0 0 0 0 0 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{voters <-}\StringTok{ }\NormalTok{df %>%}
\StringTok{  }\NormalTok{dplyr::}\KeywordTok{select}\NormalTok{(party, presjob, srv_spend,}
         \NormalTok{age, female, race_white)}
\NormalTok{voters$presjob <-}\StringTok{ }\KeywordTok{revalue}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(voters$presjob), }
                          \KeywordTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{=}\StringTok{"Approve"}\NormalTok{, }\StringTok{"2"}\NormalTok{=}\StringTok{"Approve"}\NormalTok{, }
                            \StringTok{"3"}\NormalTok{=}\StringTok{"Neutral"}\NormalTok{, }\StringTok{"4"}\NormalTok{=}\StringTok{"Neutral"}\NormalTok{,}
                            \StringTok{"5"}\NormalTok{=}\StringTok{"Neutral"}\NormalTok{, }\StringTok{"6"}\NormalTok{=}\StringTok{"Not Approve"}\NormalTok{,}
                            \StringTok{"7"}\NormalTok{=}\StringTok{"Not Approve"}\NormalTok{))}
\NormalTok{voters$srv_spend <-}\StringTok{ }\KeywordTok{revalue}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(voters$srv_spend), }
                          \KeywordTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{=}\StringTok{"Low"}\NormalTok{, }\StringTok{"2"}\NormalTok{=}\StringTok{"Low"}\NormalTok{, }\StringTok{"3"}\NormalTok{=}\StringTok{"Low"}\NormalTok{,}
                            \StringTok{"4"}\NormalTok{=}\StringTok{"Medium"}\NormalTok{, }\StringTok{"5"}\NormalTok{=}\StringTok{"Medium"}\NormalTok{,}
                            \StringTok{"997"}\NormalTok{=}\StringTok{"Medium"}\NormalTok{, }\StringTok{"6"}\NormalTok{=}\StringTok{"High"}\NormalTok{, }\StringTok{"7"}\NormalTok{=}\StringTok{"High"}\NormalTok{))}
\NormalTok{voters$female <-}\StringTok{ }\KeywordTok{revalue}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(voters$female), }
                         \KeywordTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{=}\StringTok{"Male"}\NormalTok{, }\StringTok{"1"}\NormalTok{=}\StringTok{"Female"}\NormalTok{))}
\NormalTok{voters$race_white <-}\StringTok{ }\KeywordTok{revalue}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(voters$race_white),}
                             \KeywordTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{=}\StringTok{"Non-White"}\NormalTok{, }\StringTok{"1"}\NormalTok{=}\StringTok{"White"}\NormalTok{))}

\KeywordTok{str}\NormalTok{(voters)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1200 obs. of  6 variables:
##  $ party     : chr  "Democrat" "Independent" "Republican" "Democrat" ...
##  $ presjob   : Factor w/ 3 levels "Approve","Neutral",..: 1 2 3 1 3 3 1 3 3 1 ...
##  $ srv_spend : Factor w/ 3 levels "Low","Medium",..: 3 3 1 3 1 1 3 1 1 3 ...
##  $ age       : int  56 59 53 36 42 58 38 65 43 80 ...
##  $ female    : Factor w/ 2 levels "Male","Female": 1 2 1 1 1 1 1 1 1 1 ...
##  $ race_white: Factor w/ 2 levels "Non-White","White": 2 2 2 2 2 2 2 2 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{skim}\NormalTok{(voters)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Skim summary statistics
##  n obs: 1200 
##  n variables: 6 
## 
## -- Variable type:character ------------------------------------------------
##  variable missing complete    n min max empty n_unique
##     party      81     1119 1200   8  11     0        3
## 
## -- Variable type:factor ---------------------------------------------------
##    variable missing complete    n n_unique
##      female       0     1200 1200        2
##     presjob       0     1200 1200        3
##  race_white       0     1200 1200        2
##   srv_spend       0     1200 1200        3
##                           top_counts ordered
##            Fem: 630, Mal: 570, NA: 0   FALSE
##  Not: 492, App: 453, Neu: 255, NA: 0   FALSE
##            Whi: 875, Non: 325, NA: 0   FALSE
##  Med: 491, Low: 406, Hig: 303, NA: 0   FALSE
## 
## -- Variable type:integer --------------------------------------------------
##  variable missing complete    n  mean    sd p0 p25 p50   p75 p100     hist
##       age       0     1200 1200 48.06 16.99 19  34  48 61.25   95 ▆▇▆▆▇▃▂▁
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write.csv}\NormalTok{(voters, }\DataTypeTok{file =} \StringTok{"voters.csv"}\NormalTok{, }\DataTypeTok{sep =} \StringTok{","}\NormalTok{, }
           \DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{col.names =} \OtherTok{TRUE}\NormalTok{)}

\NormalTok{voters <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"voters.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{sep =} \StringTok{","}\NormalTok{)}

\CommentTok{# Convert all the character variables to factor variables}
\NormalTok{voters <-}\StringTok{ }\NormalTok{voters%>%}
\StringTok{  }\NormalTok{dplyr::}\KeywordTok{mutate_if}\NormalTok{(}\KeywordTok{sapply}\NormalTok{(voters, is.character), as.factor)}
\end{Highlighting}
\end{Shaded}

\textbf{Breakout-room Discussion:} - Discuss the structure of the data -
Discuss the patterns of these variables - Discuss missing values and how
you would typically handle them at work - Add additional plots to
enhance your EDA where needed

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}

\KeywordTok{str}\NormalTok{(voters)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1200 obs. of  6 variables:
##  $ party     : Factor w/ 3 levels "Democrat","Independent",..: 1 2 3 1 NA 2 1 3 2 1 ...
##  $ presjob   : Factor w/ 3 levels "Approve","Neutral",..: 1 2 3 1 3 3 1 3 3 1 ...
##  $ srv_spend : Factor w/ 3 levels "High","Low","Medium": 1 1 2 1 2 2 1 2 2 1 ...
##  $ age       : int  56 59 53 36 42 58 38 65 43 80 ...
##  $ female    : Factor w/ 2 levels "Female","Male": 2 1 2 2 2 2 2 2 2 2 ...
##  $ race_white: Factor w/ 2 levels "Non-White","White": 2 2 2 2 2 2 2 2 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{skim}\NormalTok{(voters)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Skim summary statistics
##  n obs: 1200 
##  n variables: 6 
## 
## -- Variable type:factor ---------------------------------------------------
##    variable missing complete    n n_unique
##      female       0     1200 1200        2
##       party      81     1119 1200        3
##     presjob       0     1200 1200        3
##  race_white       0     1200 1200        2
##   srv_spend       0     1200 1200        3
##                            top_counts ordered
##             Fem: 630, Mal: 570, NA: 0   FALSE
##  Dem: 459, Ind: 380, Rep: 280, NA: 81   FALSE
##   Not: 492, App: 453, Neu: 255, NA: 0   FALSE
##             Whi: 875, Non: 325, NA: 0   FALSE
##   Med: 491, Low: 406, Hig: 303, NA: 0   FALSE
## 
## -- Variable type:integer --------------------------------------------------
##  variable missing complete    n  mean    sd p0 p25 p50   p75 p100     hist
##       age       0     1200 1200 48.06 16.99 19  34  48 61.25   95 ▆▇▆▆▇▃▂▁
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{describe}\NormalTok{(voters)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## voters 
## 
##  6  Variables      1200  Observations
## ---------------------------------------------------------------------------
## party 
##        n  missing distinct 
##     1119       81        3 
##                                               
## Value         Democrat Independent  Republican
## Frequency          459         380         280
## Proportion        0.41        0.34        0.25
## ---------------------------------------------------------------------------
## presjob 
##        n  missing distinct 
##     1200        0        3 
##                                               
## Value          Approve     Neutral Not Approve
## Frequency          453         255         492
## Proportion       0.378       0.212       0.410
## ---------------------------------------------------------------------------
## srv_spend 
##        n  missing distinct 
##     1200        0        3 
##                                
## Value        High    Low Medium
## Frequency     303    406    491
## Proportion  0.252  0.338  0.409
## ---------------------------------------------------------------------------
## age 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##     1200        0       73        1    48.06    19.53    22.00    25.00 
##      .25      .50      .75      .90      .95 
##    34.00    48.00    61.25    70.00    76.00 
## 
## lowest : 19 20 21 22 23, highest: 89 90 91 92 95
## ---------------------------------------------------------------------------
## female 
##        n  missing distinct 
##     1200        0        2 
##                         
## Value      Female   Male
## Frequency     630    570
## Proportion  0.525  0.475
## ---------------------------------------------------------------------------
## race_white 
##        n  missing distinct 
##     1200        0        2 
##                               
## Value      Non-White     White
## Frequency        325       875
## Proportion     0.271     0.729
## ---------------------------------------------------------------------------
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Number of incomplete cases in the dataset There are a}
\CommentTok{# number of ways to accomplish this task The first one will}
\CommentTok{# list the entire dataframe (when printed out to a pdf or}
\CommentTok{# html file) all of the observations with incomplete}
\CommentTok{# observations. The second one just count the number of}
\CommentTok{# missing data in each of the variables}

\CommentTok{# voters[!complete.cases(voters),]}
\KeywordTok{sapply}\NormalTok{(voters, function(x) }\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(x)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      party    presjob  srv_spend        age     female race_white 
##         81          0          0          0          0          0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There are still 81 observations with missing values.  Let's}
\CommentTok{# select only the data that we need before conducting the}
\CommentTok{# analysis.}

\CommentTok{# For a dataset this small, this step is not essential.  For}
\CommentTok{# large datasets encountered in practice, it's always a good}
\CommentTok{# idea to retain only the data needed for the analysis.}

\CommentTok{# Note that I did not overwrite the original dataset; I have}
\CommentTok{# stories to tell about this point.}

\CommentTok{# Number of incomplete cases in the dataset}
\NormalTok{voters2 <-}\StringTok{ }\NormalTok{voters[}\KeywordTok{complete.cases}\NormalTok{(voters), ]}

\CommentTok{# Convert all the character variables to factor variables}
\CommentTok{# voters2 <- voters%>% mutate_if(sapply(voters,}
\CommentTok{# is.character), as.factor)}


\CommentTok{# Reorder the categories of srv_spend}
\NormalTok{voters2$srv_spend <-}\StringTok{ }\KeywordTok{ordered}\NormalTok{(voters2$srv_spend, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Low"}\NormalTok{, }
    \StringTok{"Medium"}\NormalTok{, }\StringTok{"High"}\NormalTok{))}

\CommentTok{# Attach the dataste}
\KeywordTok{attach}\NormalTok{(voters2)}
\end{Highlighting}
\end{Shaded}

\textbf{Pause and Discuss: Missing values} For now, we would simply
exclude them in our analysis. \emph{In practice, you do not just want to
throw away observations without any investigation.}

\section{EDA:}\label{eda-1}

Let's start with the basic:

Recall that the Multinomial Probability Distribution takes the following
form:

\[ P(N_1 = n_1, \dots , N_J = n_j) = \frac{n!}{\prod_{j=1}^J} \prod_{j=1}^J \pi_j^{n_j} \]

Independence of X and Y in the context of a product multinomial model
means that the conditional probabilities for each Y are equal across the
rows of the table.

That is, for each \(j\),
\[\pi_{j|1} = \pi_{j|2} = \dots = \pi_{j|I} = \pi_{+j}\]

A test of independence specifies the following hypothesis:

\[
\begin{aligned}
  H_0: \pi_{ij} &= \pi_{i+}\pi_{+j} \quad \forall \quad i,j \\
  H_1: \pi_{ij} &\neq \pi_{i+}\pi_{+j} \quad \text{for some i or j}
\end{aligned}  
\]

The test of independencde in this context can be conducted by Pearson
chi-square test or likelihood ratio test, which we already discussed in
lecture 1. The Pearson chi-square test statistic takes the following
form

\[
X^2 = \sum_{i=1}^I \sum_{j=1}^J \frac{(n_{ij}-n_{i+}n_{+j}/n)^2}{n_{i+}n_{+j}/n}
\]

where \(X^2 \sim \chi^2_{(I-1)(J-1)}\)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Descriptive statistics}
\KeywordTok{str}\NormalTok{(voters2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1119 obs. of  6 variables:
##  $ party     : Factor w/ 3 levels "Democrat","Independent",..: 1 2 3 1 2 1 3 2 1 3 ...
##  $ presjob   : Factor w/ 3 levels "Approve","Neutral",..: 1 2 3 1 3 1 3 3 1 3 ...
##  $ srv_spend : Ord.factor w/ 3 levels "Low"<"Medium"<..: 3 3 1 3 1 3 1 1 3 1 ...
##  $ age       : int  56 59 53 36 58 38 65 43 80 38 ...
##  $ female    : Factor w/ 2 levels "Female","Male": 2 1 2 2 2 2 2 2 2 2 ...
##  $ race_white: Factor w/ 2 levels "Non-White","White": 2 2 2 2 2 2 2 2 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{skim}\NormalTok{(voters2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Skim summary statistics
##  n obs: 1119 
##  n variables: 6 
## 
## -- Variable type:factor ---------------------------------------------------
##    variable missing complete    n n_unique
##      female       0     1119 1119        2
##       party       0     1119 1119        3
##     presjob       0     1119 1119        3
##  race_white       0     1119 1119        2
##   srv_spend       0     1119 1119        3
##                           top_counts ordered
##            Fem: 593, Mal: 526, NA: 0   FALSE
##  Dem: 459, Ind: 380, Rep: 280, NA: 0   FALSE
##  Not: 446, App: 439, Neu: 234, NA: 0   FALSE
##            Whi: 813, Non: 306, NA: 0   FALSE
##  Med: 458, Low: 369, Hig: 292, NA: 0    TRUE
## 
## -- Variable type:integer --------------------------------------------------
##  variable missing complete    n  mean    sd p0 p25 p50 p75 p100     hist
##       age       0     1119 1119 48.25 17.01 19  34  49  62   95 ▆▇▆▆▇▅▂▁
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{describe}\NormalTok{(voters2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## voters2 
## 
##  6  Variables      1119  Observations
## ---------------------------------------------------------------------------
## party 
##        n  missing distinct 
##     1119        0        3 
##                                               
## Value         Democrat Independent  Republican
## Frequency          459         380         280
## Proportion        0.41        0.34        0.25
## ---------------------------------------------------------------------------
## presjob 
##        n  missing distinct 
##     1119        0        3 
##                                               
## Value          Approve     Neutral Not Approve
## Frequency          439         234         446
## Proportion       0.392       0.209       0.399
## ---------------------------------------------------------------------------
## srv_spend 
##        n  missing distinct 
##     1119        0        3 
##                                
## Value         Low Medium   High
## Frequency     369    458    292
## Proportion  0.330  0.409  0.261
## ---------------------------------------------------------------------------
## age 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##     1119        0       72        1    48.25    19.56       22       25 
##      .25      .50      .75      .90      .95 
##       34       49       62       71       76 
## 
## lowest : 19 20 21 22 23, highest: 89 90 91 92 95
## ---------------------------------------------------------------------------
## female 
##        n  missing distinct 
##     1119        0        2 
##                         
## Value      Female   Male
## Frequency     593    526
## Proportion   0.53   0.47
## ---------------------------------------------------------------------------
## race_white 
##        n  missing distinct 
##     1119        0        2 
##                               
## Value      Non-White     White
## Frequency        306       813
## Proportion     0.273     0.727
## ---------------------------------------------------------------------------
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Univariate Analysis}
\KeywordTok{apply}\NormalTok{(voters2, }\DecValTok{2}\NormalTok{, table)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $party
## 
##    Democrat Independent  Republican 
##         459         380         280 
## 
## $presjob
## 
##     Approve     Neutral Not Approve 
##         439         234         446 
## 
## $srv_spend
## 
##   High    Low Medium 
##    292    369    458 
## 
## $age
## 
## 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 
## 12 16 13 19 17 21 19 23 27 20 19 20 15 14 19 19 19 24 16 25 22 20 23 17 30 
## 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 
## 21 10 12  8 17 13  9 15 20 16 21 29 26 22 20 24 33 30 36 26 20 20 18 16  9 
## 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 89 90 91 92 95 
## 15 10 15  8 14 10  8 11  6 10  6  8  1  2  4  3  2  1  1  2  1  1 
## 
## $female
## 
## Female   Male 
##    593    526 
## 
## $race_white
## 
## Non-White     White 
##       306       813
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{exam_cat_var =}\StringTok{ }\NormalTok{function(var.names) \{}
    \KeywordTok{round}\NormalTok{(}\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(var.names)), }\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\KeywordTok{apply}\NormalTok{(voters2, }\DecValTok{2}\NormalTok{, exam_cat_var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $party
## var.names
##    Democrat Independent  Republican 
##        0.41        0.34        0.25 
## 
## $presjob
## var.names
##     Approve     Neutral Not Approve 
##        0.39        0.21        0.40 
## 
## $srv_spend
## var.names
##   High    Low Medium 
##   0.26   0.33   0.41 
## 
## $age
## var.names
##   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33 
## 0.01 0.01 0.01 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.01 0.01 0.02 
##   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48 
## 0.02 0.02 0.02 0.01 0.02 0.02 0.02 0.02 0.02 0.03 0.02 0.01 0.01 0.01 0.02 
##   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63 
## 0.01 0.01 0.01 0.02 0.01 0.02 0.03 0.02 0.02 0.02 0.02 0.03 0.03 0.03 0.02 
##   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78 
## 0.02 0.02 0.02 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 
##   79   80   81   82   83   84   85   89   90   91   92   95 
## 0.01 0.01 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
## 
## $female
## var.names
## Female   Male 
##   0.53   0.47 
## 
## $race_white
## var.names
## Non-White     White 
##      0.27      0.73
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# test_indep = function(data, var1, var2) \{ table <-}
\CommentTok{# xtabs(~var1 + var2, data = data) round(prop.table(table),2)}
\CommentTok{# chisq.test(table) assocstats(table) \}}

\CommentTok{# test_indep(voters2, party, presjob) xtabs(~party+presjob,}
\CommentTok{# data=voters2) round(prop.table(xtabs(~party+presjob,}
\CommentTok{# data=voters2)),2)}

\CommentTok{# Bivariate Analysis}
\NormalTok{cross_tab =}\StringTok{ }\NormalTok{function(xvar, yvar) \{}
    \KeywordTok{CrossTable}\NormalTok{(xvar, yvar, }\DataTypeTok{digits =} \DecValTok{2}\NormalTok{, }\DataTypeTok{prop.c =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.t =} \OtherTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\CommentTok{# President Approval by Party}
\KeywordTok{cross_tab}\NormalTok{(voters2$presjob, voters2$party)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |    Democrat | Independent |  Republican |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##      Approve |         331 |          88 |          20 |         439 | 
##              |      126.50 |       25.02 |       73.49 |             | 
##              |        0.75 |        0.20 |        0.05 |        0.39 | 
## -------------|-------------|-------------|-------------|-------------|
##      Neutral |         100 |          99 |          35 |         234 | 
##              |        0.17 |        4.80 |        9.47 |             | 
##              |        0.43 |        0.42 |        0.15 |        0.21 | 
## -------------|-------------|-------------|-------------|-------------|
##  Not Approve |          28 |         193 |         225 |         446 | 
##              |      131.23 |       11.40 |      115.23 |             | 
##              |        0.06 |        0.43 |        0.50 |        0.40 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         459 |         380 |         280 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Spending Sentiment by Party}
\KeywordTok{cross_tab}\NormalTok{(voters2$srv_spend, voters2$party)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |    Democrat | Independent |  Republican |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##          Low |          48 |         158 |         163 |         369 | 
##              |       70.58 |        8.53 |       54.09 |             | 
##              |        0.13 |        0.43 |        0.44 |        0.33 | 
## -------------|-------------|-------------|-------------|-------------|
##       Medium |         217 |         150 |          91 |         458 | 
##              |        4.52 |        0.20 |        4.86 |             | 
##              |        0.47 |        0.33 |        0.20 |        0.41 | 
## -------------|-------------|-------------|-------------|-------------|
##         High |         194 |          72 |          26 |         292 | 
##              |       46.00 |        7.44 |       30.32 |             | 
##              |        0.66 |        0.25 |        0.09 |        0.26 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         459 |         380 |         280 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Gender by Party}
\KeywordTok{cross_tab}\NormalTok{(voters2$female, voters2$party)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |    Democrat | Independent |  Republican |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##       Female |         270 |         172 |         151 |         593 | 
##              |        2.94 |        4.29 |        0.05 |             | 
##              |        0.46 |        0.29 |        0.25 |        0.53 | 
## -------------|-------------|-------------|-------------|-------------|
##         Male |         189 |         208 |         129 |         526 | 
##              |        3.32 |        4.83 |        0.05 |             | 
##              |        0.36 |        0.40 |        0.25 |        0.47 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         459 |         380 |         280 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Race by Party}
\KeywordTok{cross_tab}\NormalTok{(voters2$race_white, voters2$party)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |    Democrat | Independent |  Republican |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##    Non-White |         187 |          82 |          37 |         306 | 
##              |       30.12 |        4.62 |       20.45 |             | 
##              |        0.61 |        0.27 |        0.12 |        0.27 | 
## -------------|-------------|-------------|-------------|-------------|
##        White |         272 |         298 |         243 |         813 | 
##              |       11.34 |        1.74 |        7.70 |             | 
##              |        0.33 |        0.37 |        0.30 |        0.73 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         459 |         380 |         280 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Age Distribution by Party}
\KeywordTok{ggplot}\NormalTok{(voters2, }\KeywordTok{aes}\NormalTok{(}\KeywordTok{factor}\NormalTok{(party), age)) +}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(party))) +}\StringTok{ }
\StringTok{    }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Age by Party Affiliation"}\NormalTok{) +}\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{lineheight =} \DecValTok{1}\NormalTok{, }
    \DataTypeTok{face =} \StringTok{"bold"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{w271_LiveSession04_solns_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Age Distribution by President Approval}
\KeywordTok{ggplot}\NormalTok{(voters2, }\KeywordTok{aes}\NormalTok{(}\KeywordTok{factor}\NormalTok{(presjob), age)) +}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(presjob))) +}\StringTok{ }
\StringTok{    }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Age Distribution by President Approval"}\NormalTok{) +}\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{lineheight =} \DecValTok{1}\NormalTok{, }
    \DataTypeTok{face =} \StringTok{"bold"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{w271_LiveSession04_solns_files/figure-latex/unnamed-chunk-3-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Age Distribution by Spending Sentiment}
\KeywordTok{ggplot}\NormalTok{(voters2, }\KeywordTok{aes}\NormalTok{(}\KeywordTok{factor}\NormalTok{(srv_spend), age)) +}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(srv_spend))) +}\StringTok{ }
\StringTok{    }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Age Distribution by Spending Sentiment"}\NormalTok{) +}\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{lineheight =} \DecValTok{1}\NormalTok{, }
    \DataTypeTok{face =} \StringTok{"bold"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{w271_LiveSession04_solns_files/figure-latex/unnamed-chunk-3-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# President Approval by Spending Sentiment, Gender, and Race}
\KeywordTok{cross_tab}\NormalTok{(voters2$srv_spend, voters2$presjob)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |     Approve |     Neutral | Not Approve |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##          Low |          40 |          45 |         284 |         369 | 
##              |       75.82 |       13.41 |      127.48 |             | 
##              |        0.11 |        0.12 |        0.77 |        0.33 | 
## -------------|-------------|-------------|-------------|-------------|
##       Medium |         206 |         121 |         131 |         458 | 
##              |        3.86 |        6.64 |       14.55 |             | 
##              |        0.45 |        0.26 |        0.29 |        0.41 | 
## -------------|-------------|-------------|-------------|-------------|
##         High |         193 |          68 |          31 |         292 | 
##              |       53.72 |        0.79 |       62.64 |             | 
##              |        0.66 |        0.23 |        0.11 |        0.26 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         439 |         234 |         446 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cross_tab}\NormalTok{(voters2$female, voters2$presjob)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |     Approve |     Neutral | Not Approve |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##       Female |         240 |         130 |         223 |         593 | 
##              |        0.23 |        0.29 |        0.75 |             | 
##              |        0.40 |        0.22 |        0.38 |        0.53 | 
## -------------|-------------|-------------|-------------|-------------|
##         Male |         199 |         104 |         223 |         526 | 
##              |        0.26 |        0.33 |        0.85 |             | 
##              |        0.38 |        0.20 |        0.42 |        0.47 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         439 |         234 |         446 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cross_tab}\NormalTok{(voters2$race_white, voters2$presjob)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |     Approve |     Neutral | Not Approve |   Row Total | 
## -------------|-------------|-------------|-------------|-------------|
##    Non-White |         179 |          79 |          48 |         306 | 
##              |       28.95 |        3.52 |       44.85 |             | 
##              |        0.58 |        0.26 |        0.16 |        0.27 | 
## -------------|-------------|-------------|-------------|-------------|
##        White |         260 |         155 |         398 |         813 | 
##              |       10.90 |        1.33 |       16.88 |             | 
##              |        0.32 |        0.19 |        0.49 |        0.73 | 
## -------------|-------------|-------------|-------------|-------------|
## Column Total |         439 |         234 |         446 |        1119 | 
## -------------|-------------|-------------|-------------|-------------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Spending Sentiment by Party and Race}
\KeywordTok{cross_tab}\NormalTok{(voters2$female, voters2$srv_spend)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |       Low |    Medium |      High | Row Total | 
## -------------|-----------|-----------|-----------|-----------|
##       Female |       177 |       265 |       151 |       593 | 
##              |      1.76 |      2.05 |      0.09 |           | 
##              |      0.30 |      0.45 |      0.25 |      0.53 | 
## -------------|-----------|-----------|-----------|-----------|
##         Male |       192 |       193 |       141 |       526 | 
##              |      1.98 |      2.31 |      0.10 |           | 
##              |      0.37 |      0.37 |      0.27 |      0.47 | 
## -------------|-----------|-----------|-----------|-----------|
## Column Total |       369 |       458 |       292 |      1119 | 
## -------------|-----------|-----------|-----------|-----------|
## 
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cross_tab}\NormalTok{(voters2$race_white, voters2$srv_spend)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1119 
## 
##  
##              | yvar 
##         xvar |       Low |    Medium |      High | Row Total | 
## -------------|-----------|-----------|-----------|-----------|
##    Non-White |        59 |       149 |        98 |       306 | 
##              |     17.40 |      4.51 |      4.13 |           | 
##              |      0.19 |      0.49 |      0.32 |      0.27 | 
## -------------|-----------|-----------|-----------|-----------|
##        White |       310 |       309 |       194 |       813 | 
##              |      6.55 |      1.70 |      1.55 |           | 
##              |      0.38 |      0.38 |      0.24 |      0.73 | 
## -------------|-----------|-----------|-----------|-----------|
## Column Total |       369 |       458 |       292 |      1119 | 
## -------------|-----------|-----------|-----------|-----------|
## 
## 
\end{verbatim}

\section{Multinomial Logistic Regression
Model}\label{multinomial-logistic-regression-model}

We are going to use a multinomial logistic regression model to model
repondents' party affiliation using respondents' age, race, gender,
their sentiment about service spending, and president approval as
explanatory variables.

In what follow, we will discuss the model estimation, statistical
inference, model interpretation, and visualization of effect. As in
other live sessions, many discussions occur verbally in the class and
are not written in this file.

To estimate a multinomial logistic regression, we use the
\texttt{multinom()} function from the \texttt{nnet} package. It has the
same structure as basically all of the other statistical modeling
functions we have studied so far.

** Breakout-room Discussion: ** - Estimate a multinomial logistic
regression with only \texttt{age}, \texttt{female}, and
\texttt{race\_white} as explanatory variables. Call the regression
\texttt{mod.nomial1} - Discussion the estimation results. For instance,
is being a male more or less likely to be a Democrat (relative to being
a Republican)? Answer questions like this using your regression results.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# mod.nominal1 <- multinom(FORMULA, data = voters2)}
\CommentTok{# summary(YOUR ESTIMATED MODEL)}

\NormalTok{mod.nominal1 <-}\StringTok{ }\KeywordTok{multinom}\NormalTok{(party ~}\StringTok{ }\NormalTok{age +}\StringTok{ }\NormalTok{female +}\StringTok{ }\NormalTok{race_white, }\DataTypeTok{data =} \NormalTok{voters2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # weights:  15 (8 variable)
## initial  value 1229.347151 
## iter  10 value 1159.505388
## final  value 1158.296837 
## converged
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(mod.nominal1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## multinom(formula = party ~ age + female + race_white, data = voters2)
## 
## Coefficients:
##             (Intercept)          age femaleMale race_whiteWhite
## Independent  -0.8746836 -0.004691438  0.5347540       0.9388692
## Republican   -2.0040779  0.006713023  0.1967759       1.4631661
## 
## Std. Errors:
##             (Intercept)         age femaleMale race_whiteWhite
## Independent   0.2388200 0.004265186  0.1426919       0.1601704
## Republican    0.2865931 0.004646452  0.1579127       0.2025894
## 
## Residual Deviance: 2316.594 
## AIC: 2332.594
\end{verbatim}

The \emph{levels()} function show that \emph{Democrat} is stored as the
first level of the variable \emph{party}. Therefore, \emph{multinom()}
function would use it as the base level.

The estimated regressions are

\textbf{Equation 1: Independent vs.~Democrat} \[
log \left( \frac{\widehat{\pi}_{Independent}}{\widehat{\pi}_{Democrat}} \right) = -0.8747 - 0.0047age + 0.5348I(Female) + 0.9389I(White)
\]

\textbf{Equation 2: Republican vs.~Democrat} \[
log \left( \frac{\widehat{\pi}_{Republican}}{\widehat{\pi}_{Democrat}} \right) = -2.0041 + 0.0067age + 0.1968I(Female) + 1.4632I(White)
\]

\section{Statistical Inference}\label{statistical-inference}

** Breakout-room Discussion: ** - As starter, test the existance of the
age effect in the logit of independent vs democrat equation. (Hint: For
simplicity, use Wald test.) - Test the existence of effect of an
explanatory variable on all response categories

Hypothesis such as \(H_0: \beta_{jr}=0\) vs \(H_a: \beta_{jr} \ne 0\)
can be performed by Wald-type test. For instance, we want to test the
existance of the age effect in the logit of independent vs democrat
equation, we construct the following equation

\[
\frac{\hat{\beta}_{12}}{\sqrt{\widehat{Var}(\beta_{12})}} = \frac{-0.0047}{0.0043} = -1.08
\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# YOUR CODE TO BE HERE}
\KeywordTok{str}\NormalTok{(mod.nominal1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 27
##  $ n            : num [1:3] 4 0 3
##  $ nunits       : int 8
##  $ nconn        : num [1:9] 0 0 0 0 0 0 5 10 15
##  $ conn         : num [1:15] 0 1 2 3 4 0 1 2 3 4 ...
##  $ nsunits      : num 5
##  $ decay        : num 0
##  $ entropy      : logi FALSE
##  $ softmax      : logi TRUE
##  $ censored     : logi FALSE
##  $ value        : num 1158
##  $ wts          : num [1:15] 0 0 0 0 0 ...
##  $ convergence  : int 0
##  $ fitted.values: num [1:1119, 1:3] 0.291 0.374 0.291 0.291 0.291 ...
##   ..- attr(*, "dimnames")=List of 2
##   .. ..$ : chr [1:1119] "1" "2" "3" "4" ...
##   .. ..$ : chr [1:3] "Democrat" "Independent" "Republican"
##  $ residuals    : num [1:1119, 1:3] 0.709 -0.374 -0.291 0.709 -0.291 ...
##   ..- attr(*, "dimnames")=List of 2
##   .. ..$ : chr [1:1119] "1" "2" "3" "4" ...
##   .. ..$ : chr [1:3] "Democrat" "Independent" "Republican"
##  $ lev          : chr [1:3] "Democrat" "Independent" "Republican"
##  $ call         : language multinom(formula = party ~ age + female + race_white, data = voters2)
##  $ terms        :Classes 'terms', 'formula'  language party ~ age + female + race_white
##   .. ..- attr(*, "variables")= language list(party, age, female, race_white)
##   .. ..- attr(*, "factors")= int [1:4, 1:3] 0 1 0 0 0 0 1 0 0 0 ...
##   .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. ..$ : chr [1:4] "party" "age" "female" "race_white"
##   .. .. .. ..$ : chr [1:3] "age" "female" "race_white"
##   .. ..- attr(*, "term.labels")= chr [1:3] "age" "female" "race_white"
##   .. ..- attr(*, "order")= int [1:3] 1 1 1
##   .. ..- attr(*, "intercept")= int 1
##   .. ..- attr(*, "response")= int 1
##   .. ..- attr(*, ".Environment")=<environment: R_GlobalEnv> 
##   .. ..- attr(*, "predvars")= language list(party, age, female, race_white)
##   .. ..- attr(*, "dataClasses")= Named chr [1:4] "factor" "numeric" "factor" "factor"
##   .. .. ..- attr(*, "names")= chr [1:4] "party" "age" "female" "race_white"
##  $ weights      : num [1:1119, 1] 1 1 1 1 1 1 1 1 1 1 ...
##   ..- attr(*, "dimnames")=List of 2
##   .. ..$ : chr [1:1119] "1" "2" "3" "4" ...
##   .. ..$ : NULL
##  $ deviance     : num 2317
##  $ rank         : int 4
##  $ lab          : chr [1:3] "Democrat" "Independent" "Republican"
##  $ coefnames    : chr [1:4] "(Intercept)" "age" "femaleMale" "race_whiteWhite"
##  $ vcoefnames   : chr [1:4] "(Intercept)" "age" "femaleMale" "race_whiteWhite"
##  $ contrasts    :List of 2
##   ..$ female    : chr "contr.treatment"
##   ..$ race_white: chr "contr.treatment"
##  $ xlevels      :List of 2
##   ..$ female    : chr [1:2] "Female" "Male"
##   ..$ race_white: chr [1:2] "Non-White" "White"
##  $ edf          : num 8
##  $ AIC          : num 2333
##  - attr(*, "class")= chr [1:2] "multinom" "nnet"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(mod.nominal1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             (Intercept)          age femaleMale race_whiteWhite
## Independent  -0.8746836 -0.004691438  0.5347540       0.9388692
## Republican   -2.0040779  0.006713023  0.1967759       1.4631661
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{vcov}\NormalTok{(mod.nominal1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in sqrt(vcov(mod.nominal1)): NaNs produced
\end{verbatim}

\begin{verbatim}
##                             Independent:(Intercept) Independent:age
## Independent:(Intercept)                   0.2388200             NaN
## Independent:age                                 NaN     0.004265186
## Independent:femaleMale                          NaN     0.003957147
## Independent:race_whiteWhite                     NaN             NaN
## Republican:(Intercept)                    0.1569337             NaN
## Republican:age                                  NaN     0.002967266
## Republican:femaleMale                           NaN     0.003528301
## Republican:race_whiteWhite                      NaN             NaN
##                             Independent:femaleMale
## Independent:(Intercept)                        NaN
## Independent:age                        0.003957147
## Independent:femaleMale                 0.142691880
## Independent:race_whiteWhite            0.014407615
## Republican:(Intercept)                         NaN
## Republican:age                         0.002886379
## Republican:femaleMale                  0.099982334
## Republican:race_whiteWhite             0.006090098
##                             Independent:race_whiteWhite
## Independent:(Intercept)                             NaN
## Independent:age                                     NaN
## Independent:femaleMale                       0.01440761
## Independent:race_whiteWhite                  0.16017040
## Republican:(Intercept)                              NaN
## Republican:age                                      NaN
## Republican:femaleMale                        0.02336031
## Republican:race_whiteWhite                   0.09714757
##                             Republican:(Intercept) Republican:age
## Independent:(Intercept)                  0.1569337            NaN
## Independent:age                                NaN    0.002967266
## Independent:femaleMale                         NaN    0.002886379
## Independent:race_whiteWhite                    NaN            NaN
## Republican:(Intercept)                   0.2865931            NaN
## Republican:age                                 NaN    0.004646452
## Republican:femaleMale                          NaN    0.005167222
## Republican:race_whiteWhite                     NaN            NaN
##                             Republican:femaleMale
## Independent:(Intercept)                       NaN
## Independent:age                       0.003528301
## Independent:femaleMale                0.099982334
## Independent:race_whiteWhite           0.023360309
## Republican:(Intercept)                        NaN
## Republican:age                        0.005167222
## Republican:femaleMale                 0.157912730
## Republican:race_whiteWhite                    NaN
##                             Republican:race_whiteWhite
## Independent:(Intercept)                            NaN
## Independent:age                                    NaN
## Independent:femaleMale                     0.006090098
## Independent:race_whiteWhite                0.097147566
## Republican:(Intercept)                             NaN
## Republican:age                                     NaN
## Republican:femaleMale                              NaN
## Republican:race_whiteWhite                 0.202589404
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(mod.nominal1)[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.004691438
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{vcov}\NormalTok{(mod.nominal1)[}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.004265186
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(mod.nominal1)[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]/}\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{vcov}\NormalTok{(mod.nominal1)[}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.099937
\end{verbatim}

To test the existence of effect of an explanatory variable on all
response categories, we set the hypotheses as follow:

\[
H_0: \beta_{jr} = 0, \quad j=2,\dots,J \quad \text{assuming j=1 is the base category}
H_a: \beta_{jr} \ne 0, \quad \text{for some } j
\]

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(car)}
\KeywordTok{Anova}\NormalTok{(mod.nominal1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table (Type II tests)
## 
## Response: party
##            LR Chisq Df Pr(>Chisq)    
## age           5.904  2  0.0522392 .  
## female       14.367  2  0.0007592 ***
## race_white   72.677  2  < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

The numbers in the column \emph{LR Chisq} is \(-2log(\Lambda)\). For
instance, this transformed test statistic is \(14.738\) for the
explanatory \emph{female}, and its corresponding p-value
(\(Pr(>Chisq)\)) is less than 0.001.

\section{Model Interpretation}\label{model-interpretation}

** Breakout-room Discussion: ** - Interpret the estimated coefficients
of the model

To interpret the coefficients, we first exponentiate the estimated
coefficients

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{exp}\NormalTok{(}\KeywordTok{coefficients}\NormalTok{(mod.nominal1)), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             (Intercept)  age femaleMale race_whiteWhite
## Independent        0.42 1.00       1.71            2.56
## Republican         0.13 1.01       1.22            4.32
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# round(1/exp(coefficients(mod.nominal1)),2)}
\end{Highlighting}
\end{Shaded}

\emph{Note: for presentation purpose only, I use four decimal places in
the formula below.}

\(\pi_{Democrat}\) \[
\widehat{\pi}_{Democrat} = \frac{1}{1 + exp(-0.3726 -0.5425female + 0.9540white -0.0046age +0.0002srv_{spend})  + exp(-1.8061 - 0.1971female + 1.4634white + 0.0067age +0.0000srv_{spend})}
\]

\(\pi_{Independent}:\) \[
\widehat{\pi}_{Independent} = \frac{exp(-0.3726 -0.5425female + 0.9540white -0.0046age +0.0002srv_{spend}}{1 + exp(-0.3726 -0.5425female + 0.9540white -0.0046age +0.0002srv_{spend})  + exp(-1.8061 - 0.1971female + 1.4634white + 0.0067age +0.0000srv_{spend})}
\]

\(\pi_{Republican}:\) \[
\widehat{\pi}_{Republican} = \frac{exp(-1.8061 - 0.1971female + 1.4634white + 0.0067age +0.0000srv_{spend})}}{1 + exp(-0.3726 -0.5425female + 0.9540white -0.0046age +0.0002srv_{spend})  + exp(-1.8061 - 0.1971female + 1.4634white + 0.0067age +0.0000srv_{spend})}
\]

\section{Calculation of Estimated
Probabilitie3s}\label{calculation-of-estimated-probabilitie3s}

** Breakout-room Discussion ** - Estimated probabilities for each of the
observations in the sample (it's also called ``Fitted Value'')

In practice, however, one could obtaine these estimated probability by
simply call the \emph{predict()} function with the correct parameter and
a dataset from which the estimated probabilities will be calculated.

For example,

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# The columns are re-orderd to match the ordering of the}
\CommentTok{# explanatory variables in the model}
\KeywordTok{str}\NormalTok{(}\KeywordTok{summary}\NormalTok{(voters2[, }\DecValTok{2}\NormalTok{:}\DecValTok{5}\NormalTok{][}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  'table' chr [1:6, 1:4] "Low   :369  " "Medium:458  " "High  :292  " ...
##  - attr(*, "dimnames")=List of 2
##   ..$ : chr [1:6] "" "" "" "" ...
##   ..$ : chr [1:4] " srv_spend" "     age" "       presjob" "   female"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(voters2[, }\DecValTok{2}\NormalTok{:}\DecValTok{5}\NormalTok{][}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   srv_spend        age               presjob       female   
##  Low   :369   Min.   :19.00   Approve    :439   Female:593  
##  Medium:458   1st Qu.:34.00   Neutral    :234   Male  :526  
##  High  :292   Median :49.00   Not Approve:446               
##               Mean   :48.25                                 
##               3rd Qu.:62.00                                 
##               Max.   :95.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{skim}\NormalTok{(voters2[, }\DecValTok{2}\NormalTok{:}\DecValTok{5}\NormalTok{][}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Skim summary statistics
##  n obs: 1119 
##  n variables: 4 
## 
## -- Variable type:factor ---------------------------------------------------
##   variable missing complete    n n_unique
##     female       0     1119 1119        2
##    presjob       0     1119 1119        3
##  srv_spend       0     1119 1119        3
##                           top_counts ordered
##            Fem: 593, Mal: 526, NA: 0   FALSE
##  Not: 446, App: 439, Neu: 234, NA: 0   FALSE
##  Med: 458, Low: 369, Hig: 292, NA: 0    TRUE
## 
## -- Variable type:integer --------------------------------------------------
##  variable missing complete    n  mean    sd p0 p25 p50 p75 p100     hist
##       age       0     1119 1119 48.25 17.01 19  34  49  62   95 ▆▇▆▆▇▅▂▁
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(mod.nominal1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## multinom(formula = party ~ age + female + race_white, data = voters2)
## 
## Coefficients:
##             (Intercept)          age femaleMale race_whiteWhite
## Independent  -0.8746836 -0.004691438  0.5347540       0.9388692
## Republican   -2.0040779  0.006713023  0.1967759       1.4631661
## 
## Std. Errors:
##             (Intercept)         age femaleMale race_whiteWhite
## Independent   0.2388200 0.004265186  0.1426919       0.1601704
## Republican    0.2865931 0.004646452  0.1579127       0.2025894
## 
## Residual Deviance: 2316.594 
## AIC: 2332.594
\end{verbatim}

\section{\texorpdfstring{Estimated probabilities for each of the
observations in the sample (it's also called ``Fitted
Value'')}{Estimated probabilities for each of the observations in the sample (it's also called Fitted Value)}}\label{estimated-probabilities-for-each-of-the-observations-in-the-sample-its-also-called-fitted-value}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pi.hat <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(}\DataTypeTok{object =} \NormalTok{mod.nominal1, }\DataTypeTok{newdata =} \NormalTok{voters2, }\DataTypeTok{type =} \StringTok{"probs"}\NormalTok{)}
\KeywordTok{cbind}\NormalTok{(}\KeywordTok{head}\NormalTok{(voters2[, }\DecValTok{2}\NormalTok{:}\DecValTok{6}\NormalTok{][}\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)]), }\KeywordTok{round}\NormalTok{(}\KeywordTok{head}\NormalTok{(pi.hat), }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   age female race_white Democrat Independent Republican
## 1  56   Male      White     0.29        0.41       0.30
## 2  59 Female      White     0.37        0.30       0.32
## 3  53   Male      White     0.29        0.41       0.29
## 4  36   Male      White     0.29        0.45       0.26
## 6  58   Male      White     0.29        0.40       0.30
## 7  38   Male      White     0.29        0.44       0.27
\end{verbatim}

\textbf{Pasue and Discuss: Interpreting the estimated probabilities}


\end{document}
